language: objective-c
osx_image: xcode8
dist: trusty
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SwiftLCS.xcworkspace
  - IOS_FRAMEWORK_SCHEME="SwiftLCS iOS"
  - OSX_FRAMEWORK_SCHEME="SwiftLCS OSX"
  - TVOS_FRAMEWORK_SCHEME="SwiftLCS tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="SwiftLCS watchOS"
  - IOS_SDK=iphonesimulator10.0
  - OSX_SDK=macosx10.12
  - TVOS_SDK=appletvsimulator10.0
  - WATCHOS_SDK=watchsimulator3.0
  - EXAMPLE_SCHEME="SwiftLCS Example"
  - SWIFT_VERSION=swift-3.0
  - SWIFTENV_ROOT="$HOME/.swiftenv"
  - PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
matrix:
  include:
    - os: osx
      env: DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"  BUILD_EXAMPLE="NO"
    - os: osx
      env: DESTINATION="OS=2.0,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"  BUILD_EXAMPLE="NO"
    - os: osx
      env: DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - os: osx
      env: DESTINATION="OS=8.1,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"  BUILD_EXAMPLE="NO"
    - os: osx
      env: DESTINATION="OS=10.0,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO"  BUILD_EXAMPLE="NO"
    - os: osx
      env: DESTINATION="OS=9.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="NO"  BUILD_EXAMPLE="NO"
    - os: osx
      env: DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="NO"  BUILD_EXAMPLE="NO"
    - os: linux
      sudo: required
      language: generic
before_install:
  - .travis/install_cocoapods.sh
install:
  - .travis/install_swift.sh
script:
  - set -o pipefail
  - .travis/build.sh Debug "$SCHEME"
  - .travis/build.sh Release "$SCHEME"
  - .travis/build-example.sh Debug "$EXAMPLE_SCHEME"
